spring:
  application:
    name: booking-service
  data:
    mongodb:
      uri: mongodb://afibarra:4rm4nd0.fl0r35.1b4rr4@booking-shard-00-00.fmrp7.mongodb.net:27017,booking-shard-00-02.fmrp7.mongodb.net:27017,booking-shard-00-01.fmrp7.mongodb.net:27017/admin?ssl=true&replicaSet=atlas-xfl028-shard-0&readPreference=primary&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1
      database: bookingservice
  sleuth:
    sampler:
      probability: 1.0
    web:
      additional-skip-pattern: /health
    mongodb:
      enabled: true
    redis:
      enabled: true

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path:
      path-mapping:
        health: /health
  endpoint:
    health:
      enabled: true

logging:
  level:
    root: info
  #    me:
  #      afibarra:
  #        servicebooking: debug
  #    org:
  #      springframework:
  #        data:
  #          mongodb:
  #            core:
  #              ReactiveMongoTemplate: debug
  #        web:
  #          reactive:
  #            result:
  #              method:
  #                annotation:
  #                  RequestMappingHandlerMapping: debug
  #            function:
  #              client:
  #                WebClient: debug
  #          server:
  #            adapter:
  #              HttpWebHandlerAdapter: debug
  pattern:
    level: "[${spring.application.name}/%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n"
